=== GreenWaves-Technologies/gap_sdk/rtos/mbed-os/tools/psa/partition_description_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "schema for a partition description.",
  "type": "object",
  "required": ["name", "type", "priority", "id", "entry_point", "stack_size", "heap_size", "source_files"],
  "anyOf": [
    {"required" : ["services"]},
    {"required" : ["irqs"]}
  ],
  "properties": {
    "name": {
      "description": "Alphanumeric C macro for referring to a partition. (all capital)",
      "$ref": "#/definitions/c_macro"
    },
    "type": {
      "description": "Whether the partition is unprivileged or part of the trusted computing base.",
      "enum": ["APPLICATION-ROT", "PSA-ROT"]
    },
    "priority": {
      "description": "Partition task priority.",
      "enum": ["LOW", "NORMAL", "HIGH"]
    },
    "id": {
      "description": "Partition numeric unique positive identifier. (must be a positive 8 bytes hex string)",
      "type": "string",
      "pattern": "^0x[0-7][0-9a-fA-F]{7}$"
    },
    "entry_point": {
      "description": "C symbol name of the partition's entry point. (unmangled, use extern C if needed)",
      "$ref": "#/definitions/c_symbol"
    },
    "stack_size": {
      "description": "Partition's task stack size in bytes.",
      "$ref": "#/definitions/positive_integer_or_hex_string"
    },
    "heap_size": {
      "description": "Partition's task heap size in bytes.",
      "$ref": "#/definitions/positive_integer_or_hex_string"
    },
    "mmio_regions": {
      "description": "List of Memory-Mapped IO region objects which the partition has access to.",
      "type": "array",
      "items": {
        "anyOf": [{
            "$ref": "#/definitions/named_region"
          },
          {
            "$ref": "#/definitions/numbered_region"
          }
        ]
      },
      "uniqueItems": true
    },
    "services": {
      "description": "List of RoT Service objects which the partition implements.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/service"
      },
      "uniqueItems": true
    },
    "extern_sids": {
      "description": "List of SID which the partition code depends on and allowed to access.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/c_macro"
      },
      "uniqueItems": true
    },
    "source_files": {
      "description": "List of source files relative to PSA Manifest file. A Secure Partition is built from explicit file list.",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9-_./]+$"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "irqs": {
      "description": "List of IRQ objects which the partition implements.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/irq"
      },
      "uniqueItems": true
    }
  },
  "definitions": {
    "c_macro": {
      "type": "string",
      "pattern": "^[A-Z_][A-Z0-9_]*$"
    },
    "c_symbol": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*$"
    },
    "hex_string": {
      "type": "string",
      "pattern": "^0x(0*[1-9a-fA-F][0-9a-fA-F]*)$",
      "minLength": 3,
      "maxLength": 10
    },
    "positive_integer": {
      "type": "integer",
      "exclusiveMinimum": true,
      "minimum": 0
    },
    "positive_integer_or_hex_string": {
      "oneOf": [{
          "$ref": "#/definitions/positive_integer"
        },
        {
          "$ref": "#/definitions/hex_string"
        }
      ]
    },
    "named_region": {
      "description": "MMIO region which is described by it's C macro name and access permissions.",
      "required": ["name", "permission"],
      "properties": {
        "name": {
          "description": "Alphanumeric C macro for referring to the region.",
          "$ref": "#/definitions/c_macro"
        },
        "permission": {
          "description": "Access permissions for the region.",
          "enum": ["READ-ONLY", "READ-WRITE"]
        }
      }
    },
    "numbered_region": {
      "description": "MMIO region which is described by it's base address, size and access permissions.",
      "required": ["base", "size", "permission"],
      "properties": {
        "base": {
          "description": "The base address of the region.",
          "$ref": "#/definitions/hex_string"
        },
        "size": {
          "description": "Size in bytes of the region.",
          "$ref": "#/definitions/positive_integer_or_hex_string"
        },
        "permission": {
          "description": "Access permissions for the region.",
          "enum": ["READ-ONLY", "READ-WRITE"]
        }
      }
    },
    "service": {
      "required": ["name", "identifier", "non_secure_clients", "signal"],
      "properties": {
        "name": {
          "description": "Alphanumeric C macro for referring to a RoT Service from source code (all capital)",
          "$ref": "#/definitions/c_macro"
        },
        "identifier": {
          "description": "The integer value of the NAME field",
          "$ref": "#/definitions/positive_integer_or_hex_string"
        },
        "non_secure_clients": {
          "description": "Denote whether the RoT Service is exposed to non-secure clients.",
          "type": "boolean"
        },
        "signal": {
          "description": "Alphanumeric C macro for referring to the RoT Service's signal value. (all capital)",
          "$ref": "#/definitions/c_macro"
        },
        "minor_version": {
          "description": "Optional: Minor version number of the RoT Service's interface.",
          "$ref": "#/definitions/positive_integer",
          "default": 1
        },
        "minor_policy": {
          "description": "Optional: Minor version policy to apply on connections to the RoT Service.",
          "enum": ["STRICT", "RELAXED"],
          "default": "STRICT"
        }
      }
    },
    "irq": {
      "required": ["line_num", "signal"],
      "properties": {
        "line_num": {
          "description": "Interrupt line number for registering to ISR table entry and enable/disable the specific IRQ once received.",
          "type": "integer",
          "minimum": 0
        },
        "signal": {
          "description": "Alphanumeric C macro for referring to the IRQ's signal value. (all capital)",
          "$ref": "#/definitions/c_macro"
        }
      }
    }
  }
}

=== GreenWaves-Technologies/gap_sdk/rtos/mbed-os/TESTS/psa/spm_server/part1_psa.json
{
  "name": "SERVER_TEST_PART1",
  "type": "APPLICATION-ROT",
  "priority": "NORMAL",
  "id": "0x00000002",
  "entry_point": "part1_main",
  "stack_size": "0x400",
  "heap_size": "0x400",
  "services": [{
      "name": "CONTROL",
      "identifier": "0x00001A01",
      "signal": "CONTROL_MSK",
      "non_secure_clients": true,
      "minor_version": 5,
      "minor_policy": "RELAXED"
    },
    {
      "name": "TEST",
      "identifier": "0x00001A02",
      "signal": "TEST_MSK",
      "non_secure_clients": true,
      "minor_version": 12,
      "minor_policy": "STRICT"
    }
  ],
  "extern_sids": [
    "ROT_SRV_REVERSE",
    "ROT_SRV_DB_TST"
  ],
  "source_files": [
    "COMPONENT_SPE/partition.c"
  ]
}

=== GreenWaves-Technologies/gap_sdk/rtos/mbed-os/components/TARGET_PSA/services/storage/its/pits_psa.json
{
    "name": "ITS",
    "type": "APPLICATION-ROT",
    "priority": "NORMAL",
    "id": "0x0000000A",
    "entry_point": "its_entry",
    "stack_size": "0x800",
    "heap_size": "0x400",
    "services": [{
        "name": "PSA_ITS_GET",
        "identifier": "0x00011A00",
        "signal": "PSA_ITS_GET_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      },
      {
        "name": "PSA_ITS_SET",
        "identifier": "0x00011A01",
        "signal": "PSA_ITS_SET_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      },
      {
        "name": "PSA_ITS_INFO",
        "identifier": "0x00011A02",
        "signal": "PSA_ITS_INFO_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      },
      {
        "name": "PSA_ITS_REMOVE",
        "identifier": "0x00011A03",
        "signal": "PSA_ITS_REMOVE_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      },
      {
        "name": "PSA_ITS_RESET",
        "identifier": "0x00011A04",
        "signal": "PSA_ITS_RESET_MSK",
        "non_secure_clients": false,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      }
    ],
    "source_files": [
      "COMPONENT_SPE/its_partition.c"
    ]
  }

=== GreenWaves-Technologies/gap_sdk/rtos/mbed-os/components/TARGET_PSA/services/crypto/crypto_partition_psa.json
{
  "name": "CRYPTO_SRV",
  "type": "APPLICATION-ROT",
  "priority": "NORMAL",
  "id": "0x00000023",
  "entry_point": "crypto_main",
  "stack_size": "0x4000",
  "heap_size": "0x400",
  "services": [
    {
      "name": "PSA_CRYPTO_INIT_ID",
      "identifier": "0x00000F00",
      "signal": "PSA_CRYPTO_INIT",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_MAC_ID",
      "identifier": "0x00000F01",
      "signal": "PSA_MAC",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_HASH_ID",
      "identifier": "0x00000F02",
      "signal": "PSA_HASH",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_ASYMMETRIC_ID",
      "identifier": "0x00000F03",
      "signal": "PSA_ASYMMETRIC",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_SYMMETRIC_ID",
      "identifier": "0x00000F04",
      "signal": "PSA_SYMMETRIC",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_AEAD_ID",
      "identifier": "0x00000F05",
      "signal": "PSA_AEAD",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_KEY_MNG_ID",
      "identifier": "0x00000F06",
      "signal": "PSA_KEY_MNG",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_RNG_ID",
      "identifier": "0x00000F07",
      "signal": "PSA_RNG",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_CRYPTO_FREE_ID",
      "identifier": "0x00000F08",
      "signal": "PSA_CRYPTO_FREE",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_GENERATOR_ID",
      "identifier": "0x00000F09",
      "signal": "PSA_GENERATOR",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    },
    {
      "name": "PSA_ENTROPY_ID",
      "identifier": "0x00000F0A",
      "signal": "PSA_ENTROPY_INJECT",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "STRICT"
    }
  ],
  "extern_sids": [
    "PSA_ITS_GET",
    "PSA_ITS_SET",
    "PSA_ITS_INFO",
    "PSA_ITS_REMOVE"
  ],
  "source_files": [
    "COMPONENT_SPE/psa_crypto_partition.c"
  ]
}

=== GreenWaves-Technologies/gap_sdk/rtos/mbed-os/TESTS/psa/crypto_access_control/crypto_acl_tests_partition_psa.json
{
  "name": "CRYPTO_ACL_TEST",
  "type": "APPLICATION-ROT",
  "priority": "NORMAL",
  "id": "0x00000080",
  "entry_point": "test_partition_main",
  "stack_size": "0x200",
  "heap_size": "0x400",
  "services": [
    {
      "name": "CRYPTO_CREATE_PERSISTENT_KEY",
      "identifier": "0x00000200",
      "signal": "CRYPTO_CREATE_PERSISTENT_KEY_MSK",
      "non_secure_clients": true,
      "minor_version": 1,
      "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_GENERATE_KEY",
        "identifier": "0x00000201",
        "signal": "CRYPTO_GENERATE_KEY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_OPEN_PERSISTENT_KEY",
        "identifier": "0x00000202",
        "signal": "CRYPTO_OPEN_PERSISTENT_KEY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_CLOSE_KEY",
        "identifier": "0x00000203",
        "signal": "CRYPTO_CLOSE_KEY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_SET_KEY_POLICY",
        "identifier": "0x00000204",
        "signal": "CRYPTO_SET_KEY_POLICY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_DESTROY_KEY",
        "identifier": "0x00000205",
        "signal": "CRYPTO_DESTROY_KEY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_GET_KEY_INFO",
        "identifier": "0x00000206",
        "signal": "CRYPTO_GET_KEY_INFO_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_GET_KEY_POLICY",
        "identifier": "0x00000207",
        "signal": "CRYPTO_GET_KEY_POLICY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    },
    {
        "name": "CRYPTO_IMPORT_KEY",
        "identifier": "0x00000208",
        "signal": "CRYPTO_IMPORT_KEY_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
    }
  ],
  "extern_sids": [
    "PSA_KEY_MNG_ID"
  ],
  "source_files": [
    "COMPONENT_SPE/test_partition.c"
  ]
}

=== GreenWaves-Technologies/gap_sdk/rtos/mbed-os/components/TARGET_PSA/services/platform/platform_psa.json
{
    "name": "PLATFORM",
    "type": "APPLICATION-ROT",
    "priority": "NORMAL",
    "id": "0x00000008",
    "entry_point": "platform_partition_entry",
    "stack_size": "0x400",
    "heap_size": "0x400",
    "services": [{
        "name": "PSA_PLATFORM_LC_GET",
        "identifier": "0x00011000",
        "signal": "PSA_PLATFORM_LC_GET_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      },
      {
        "name": "PSA_PLATFORM_LC_SET",
        "identifier": "0x00011001",
        "signal": "PSA_PLATFORM_LC_SET_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      },
      {
        "name": "PSA_PLATFORM_SYSTEM_RESET",
        "identifier": "0x00011002",
        "signal": "PSA_PLATFORM_SYSTEM_RESET_MSK",
        "non_secure_clients": true,
        "minor_version": 1,
        "minor_policy": "RELAXED"
      }
    ],
    "extern_sids": [
      "PSA_ITS_RESET"
    ],
    "source_files": [
      "COMPONENT_SPE/platform_partition.c"
    ]
  }
